[package]
name = "lhm-sys"
version = "0.1.1"
edition = "2024"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/jacobtread/lhm-service"
readme = "README.md"
description = "Wrapper around Libre Hardware Monitor to request hardware (and temperatures)"

[features]
default = ["static"]
dylib = []
static = []

[dependencies]
# Shared structures
lhm-shared = { version = "0.2.0", path = "../lhm-shared" }
